name = "ion"

[install]
completion=true
quiet=false
compile="min"
optimize=2

[sysimg]
incremental=true
filter_stdlibs=false

[sysimg.precompile]
statements_file = ["statements.jl"]

[application]
incremental=true
filter_stdlibs=false

[application.precompile]
statements_file = ["statements.jl"]

[download]
host="github.com"
user="Roger-luo"
repo="IonCLI.jl"
