name = "ion"

[install]
completion=true
quiet=false
compile="min"
optimize=2

[sysimg]
incremental=true
filter_stdlibs=false

[sysimg.precompile]
execution_file = ["deps/precompile.jl"]

[application]
incremental=true
filter_stdlibs=false
c_driver_program = "deps/wrapper.c"

[application.precompile]
execution_file = ["deps/precompile.jl"]

[download]
host="github.com"
user="Roger-luo"
repo="IonCLI.jl"
