name: Application
on:
    push:
      # Sequence of patterns matched against refs/tags
      tags:
        - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  
jobs:
  build:
    name: Build Application
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.5']
        os: [ubuntu-latest, macOS-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Build project # This would actually build your project, using zip for an example artifact
      uses: julia-actions/setup-julia@v1
      with:
        version: ${{ matrix.julia-version }}
    - run: julia --project -e "using Pkg; Pkg.instantiate()"
    - run: julia --project -e "using Pkg; Pkg.status()"
    - run: |
        julia --project deps/build.jl app tarball
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./build/*.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
